spring:
  profiles:
    active: dev
    include: secret, matching

logging:
  level:
    org.springframework.web.socket.config.WebSocketMessageBrokerStats: ERROR
    root: info
  config: classpath:logback-spring.xml

websocket:
  port: 8080
  endpoint: /ws
  topic: /room
  request: /chat

