spring:
  profiles:
    include: secret, matching

logging:
  level:
    org.springframework.web.socket.config.WebSocketMessageBrokerStats: ERROR

websocket:
  port: 8082
  endpoint: /ws
  topic: /room
  request: /chat